### ISSUE TITLE
Create preflight function for performed_actions table type

### ISSUE THREAD

**Issue by Seesam24601** [Seesam24601/TAMMI#29]
`output_tables.md` specifies a table type called `performed_actions`. This is specifies the result from models like `unconstrained`. In addition to being an output, this table type is ingesting by the necessary actions function type.

### Tasks

- [ ] Create a preflight function to enforce the specifications of the `performed_actions` table
- [ ] Place this requirement within models as necessary
- [ ] Place this requirement in functions of the necessary actions function type

**Comment by Seesam24601** [comment]
Not sure how necessary this is since my philosophy behind preflight tests has been to ensure the user-supplied tables and functions meet the program's specifications. May be useful for debugging though?

**Comment by Seesam24601** [comment]
The annual_adjustment function type also includes the `performed_actions` table type. See #41.

**Comment by Seesam24601** [comment]
Also, consider renaming the `actions` table in both the traditional and unconstrained models to `performed_actions` to maintain clarity between the models, the user-suppliable functions, and the output documentation.

**Comment by Seesam24601** [comment]
Consider completing #18 at the same time.
